/**
 * speedsets.js
 * 5 Speed Practice Question Sets for STC Portal
 * Each set: array of { q, a, o[] }
 * Usage: window.SP_SETS['set1'] etc.
 */

window.SP_SETS = {

  /* ══════════════════════════════════════════
     SET 1 — Mixed Science
  ══════════════════════════════════════════ */
  set1: [
    { q: "What is the chemical symbol for Gold?", a: "Au", o: ["Au", "Ag", "Gd", "Go"] },
    { q: "How many bones are in the adult human body?", a: "206", o: ["206", "208", "212", "196"] },
    { q: "What is the atomic number of Carbon?", a: "6", o: ["6", "12", "8", "4"] },
    { q: "Which gas is most abundant in Earth's atmosphere?", a: "Nitrogen", o: ["Nitrogen", "Oxygen", "Carbon Dioxide", "Argon"] },
    { q: "What is the powerhouse of the cell?", a: "Mitochondria", o: ["Mitochondria", "Nucleus", "Ribosome", "Golgi Body"] },
    { q: "What is the SI unit of electric current?", a: "Ampere", o: ["Ampere", "Volt", "Watt", "Ohm"] },
    { q: "Speed of sound in air (approx.) = ?", a: "343 m/s", o: ["343 m/s", "300 m/s", "400 m/s", "3×10⁸ m/s"] },
    { q: "What is the pH of pure water?", a: "7", o: ["7", "0", "14", "5.5"] },
    { q: "Which planet is closest to the Sun?", a: "Mercury", o: ["Mercury", "Venus", "Earth", "Mars"] },
    { q: "DNA stands for?", a: "Deoxyribonucleic Acid", o: ["Deoxyribonucleic Acid", "Diribonucleic Acid", "Deoxyribose Acid", "Dynamic Nucleic Acid"] },
    { q: "What is the chemical formula for water?", a: "H₂O", o: ["H₂O", "HO₂", "H₂O₂", "H₃O"] },
    { q: "Newton's 2nd Law: F = ?", a: "ma", o: ["ma", "mv", "mg", "m/a"] },
    { q: "The unit of frequency is?", a: "Hertz", o: ["Hertz", "Newton", "Pascal", "Joule"] },
    { q: "Photosynthesis produces which gas?", a: "Oxygen", o: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"] },
    { q: "The boiling point of water at sea level = ?", a: "100°C", o: ["100°C", "90°C", "110°C", "212°F... wait, 100°C"] },
    { q: "Atomic number of Hydrogen = ?", a: "1", o: ["1", "2", "0", "3"] },
    { q: "Which vitamin is produced by sunlight?", a: "Vitamin D", o: ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin B12"] },
    { q: "The hardest natural substance is?", a: "Diamond", o: ["Diamond", "Quartz", "Topaz", "Corundum"] },
    { q: "Light year is a unit of?", a: "Distance", o: ["Distance", "Time", "Speed", "Energy"] },
    { q: "Normal human body temperature = ?", a: "37°C", o: ["37°C", "35°C", "38.5°C", "36°C"] },
    { q: "The Earth revolves around the Sun in approximately?", a: "365.25 days", o: ["365.25 days", "360 days", "366 days", "364 days"] },
    { q: "Chemical symbol for Iron?", a: "Fe", o: ["Fe", "Ir", "In", "Fr"] },
    { q: "Which organ pumps blood in the human body?", a: "Heart", o: ["Heart", "Lungs", "Liver", "Kidney"] },
    { q: "The smallest planet in the solar system?", a: "Mercury", o: ["Mercury", "Mars", "Pluto", "Venus"] },
    { q: "Electrons have which charge?", a: "Negative", o: ["Negative", "Positive", "Neutral", "Variable"] },
    { q: "The freezing point of water = ?", a: "0°C", o: ["0°C", "-10°C", "4°C", "32°C"] },
    { q: "Which force keeps planets in orbit?", a: "Gravity", o: ["Gravity", "Magnetism", "Friction", "Electrostatic"] },
    { q: "Number of chromosomes in a human cell?", a: "46", o: ["46", "23", "48", "44"] },
    { q: "The process of water turning to vapour = ?", a: "Evaporation", o: ["Evaporation", "Condensation", "Sublimation", "Precipitation"] },
    { q: "Which gas do plants absorb for photosynthesis?", a: "CO₂", o: ["CO₂", "O₂", "N₂", "H₂"] },
  ],

  /* ══════════════════════════════════════════
     SET 2 — Computer Science
  ══════════════════════════════════════════ */
  set2: [
    { q: "What does CPU stand for?", a: "Central Processing Unit", o: ["Central Processing Unit", "Core Processing Unit", "Computer Power Unit", "Central Program Utility"] },
    { q: "What does RAM stand for?", a: "Random Access Memory", o: ["Random Access Memory", "Read Access Memory", "Rapid Access Module", "Random Array Memory"] },
    { q: "Binary: 1010 in decimal = ?", a: "10", o: ["10", "12", "8", "14"] },
    { q: "What does HTML stand for?", a: "HyperText Markup Language", o: ["HyperText Markup Language", "High Transfer Markup Language", "Hyperlink Text Machine Language", "HyperTool Markup Language"] },
    { q: "Which data structure uses LIFO?", a: "Stack", o: ["Stack", "Queue", "Array", "Linked List"] },
    { q: "Which data structure uses FIFO?", a: "Queue", o: ["Queue", "Stack", "Tree", "Graph"] },
    { q: "What is O(1) called?", a: "Constant Time", o: ["Constant Time", "Linear Time", "Log Time", "Quadratic Time"] },
    { q: "What does SQL stand for?", a: "Structured Query Language", o: ["Structured Query Language", "Simple Query Language", "Sequential Query Logic", "Standard Query Layer"] },
    { q: "The Internet uses which protocol?", a: "TCP/IP", o: ["TCP/IP", "FTP", "HTTP only", "DNS"] },
    { q: "In binary, 255 = ?", a: "11111111", o: ["11111111", "11111110", "11110111", "10111111"] },
    { q: "Which language is known as the 'mother of languages'?", a: "C", o: ["C", "Assembly", "Fortran", "BASIC"] },
    { q: "What is the full form of URL?", a: "Uniform Resource Locator", o: ["Uniform Resource Locator", "Universal Resource Link", "Unified Routing Layer", "Universal Reference Locator"] },
    { q: "Which sorting algorithm has O(n log n) average case?", a: "Merge Sort", o: ["Merge Sort", "Bubble Sort", "Insertion Sort", "Selection Sort"] },
    { q: "What does GUI stand for?", a: "Graphical User Interface", o: ["Graphical User Interface", "General Use Input", "Grid Utility Interface", "Graphic Unit Integration"] },
    { q: "What is the base of hexadecimal?", a: "16", o: ["16", "8", "10", "2"] },
    { q: "A byte consists of how many bits?", a: "8", o: ["8", "4", "16", "10"] },
    { q: "Which of these is NOT an OS?", a: "Java", o: ["Java", "Linux", "Windows", "macOS"] },
    { q: "What does OOP stand for?", a: "Object-Oriented Programming", o: ["Object-Oriented Programming", "Open Operation Protocol", "Output-Oriented Processing", "Object Ordering Procedure"] },
    { q: "A primary key in a database must be?", a: "Unique and Not Null", o: ["Unique and Not Null", "Only Unique", "Only Not Null", "Can repeat sometimes"] },
    { q: "What does DNS resolve?", a: "Domain names to IP addresses", o: ["Domain names to IP addresses", "IP to MAC addresses", "URLs to HTML", "HTTP to HTTPS"] },
    { q: "What does 'git commit' do?", a: "Saves staged changes to history", o: ["Saves staged changes to history", "Pushes to remote", "Merges branches", "Clones a repo"] },
    { q: "Which symbol is used for single-line comment in Python?", a: "#", o: ["#", "//", "/*", "--"] },
    { q: "In CSS, 'float:right' does what?", a: "Moves element to the right", o: ["Moves element to the right", "Rotates element", "Fixes position", "Changes opacity"] },
    { q: "HTTP status 404 means?", a: "Not Found", o: ["Not Found", "Server Error", "Forbidden", "Redirect"] },
    { q: "Which of these is a NoSQL database?", a: "MongoDB", o: ["MongoDB", "MySQL", "PostgreSQL", "SQLite"] },
    { q: "What is a compiler?", a: "Translates source code to machine code", o: ["Translates source code to machine code", "Runs code line by line", "Debugs code", "Stores code"] },
    { q: "In Python, what does len([1,2,3]) return?", a: "3", o: ["3", "2", "4", "Error"] },
    { q: "Which protocol is used for secure web browsing?", a: "HTTPS", o: ["HTTPS", "FTP", "SMTP", "HTTP"] },
    { q: "A recursive function must have a?", a: "Base case", o: ["Base case", "Loop", "Array", "Class"] },
    { q: "What does API stand for?", a: "Application Programming Interface", o: ["Application Programming Interface", "Automated Program Integration", "Application Processor Input", "Advanced Protocol Interface"] },
  ],

  /* ══════════════════════════════════════════
     SET 3 — Chemistry
  ══════════════════════════════════════════ */
  set3: [
    { q: "The chemical formula for table salt?", a: "NaCl", o: ["NaCl", "KCl", "NaF", "CaCl₂"] },
    { q: "Atomic number of Oxygen = ?", a: "8", o: ["8", "16", "6", "10"] },
    { q: "Which gas is called laughing gas?", a: "N₂O", o: ["N₂O", "NO₂", "CO₂", "SO₂"] },
    { q: "Acid + Base → ?", a: "Salt + Water", o: ["Salt + Water", "Salt + Gas", "Water only", "Oxide + Water"] },
    { q: "The pH of a strong acid is?", a: "Less than 7", o: ["Less than 7", "Greater than 7", "Equal to 7", "Equal to 14"] },
    { q: "Avogadro's number = ?", a: "6.022 × 10²³", o: ["6.022 × 10²³", "6.022 × 10²¹", "3.14 × 10²³", "9.8 × 10²³"] },
    { q: "Which element has symbol 'K'?", a: "Potassium", o: ["Potassium", "Krypton", "Calcium", "Copper"] },
    { q: "The process of a solid directly turning into gas?", a: "Sublimation", o: ["Sublimation", "Evaporation", "Condensation", "Deposition"] },
    { q: "Which type of bond involves sharing electrons?", a: "Covalent", o: ["Covalent", "Ionic", "Metallic", "Hydrogen"] },
    { q: "Mole is the SI unit of?", a: "Amount of substance", o: ["Amount of substance", "Mass", "Volume", "Concentration"] },
    { q: "The chemical formula for glucose?", a: "C₆H₁₂O₆", o: ["C₆H₁₂O₆", "C₆H₁₀O₅", "CH₂O", "C₁₂H₂₂O₁₁"] },
    { q: "Which is the most electronegative element?", a: "Fluorine", o: ["Fluorine", "Oxygen", "Chlorine", "Nitrogen"] },
    { q: "What is the valency of Carbon?", a: "4", o: ["4", "2", "6", "3"] },
    { q: "Name the gas produced when zinc reacts with HCl?", a: "Hydrogen", o: ["Hydrogen", "Chlorine", "Oxygen", "Helium"] },
    { q: "What is the chemical formula of baking soda?", a: "NaHCO₃", o: ["NaHCO₃", "Na₂CO₃", "NaOH", "NaCl"] },
    { q: "Electronegativity increases going?", a: "Across a period (left to right)", o: ["Across a period (left to right)", "Down a group", "Across a period (right to left)", "Up a group"] },
    { q: "Which gas turns limewater milky?", a: "CO₂", o: ["CO₂", "SO₂", "HCl gas", "O₂"] },
    { q: "The number of electrons in a neutral Carbon atom?", a: "6", o: ["6", "12", "8", "4"] },
    { q: "Isotopes have the same number of?", a: "Protons", o: ["Protons", "Neutrons", "Electrons", "Nucleons"] },
    { q: "What type of reaction releases energy?", a: "Exothermic", o: ["Exothermic", "Endothermic", "Redox", "Decomposition"] },
    { q: "The chemical symbol for Silver?", a: "Ag", o: ["Ag", "Si", "Sn", "Sr"] },
    { q: "What is the formula of sulphuric acid?", a: "H₂SO₄", o: ["H₂SO₄", "HNO₃", "HCl", "H₃PO₄"] },
    { q: "An atom with a negative charge is called?", a: "Anion", o: ["Anion", "Cation", "Isotope", "Ion"] },
    { q: "What is the lightest element?", a: "Hydrogen", o: ["Hydrogen", "Helium", "Lithium", "Boron"] },
    { q: "Period number in the periodic table represents?", a: "Number of electron shells", o: ["Number of electron shells", "Atomic number", "Number of protons", "Valency"] },
    { q: "Strong acids are?", a: "Fully ionized in water", o: ["Fully ionized in water", "Partially ionized", "Non-ionized", "Neutral in water"] },
    { q: "What is the formula of ozone?", a: "O₃", o: ["O₃", "O₂", "O", "O₄"] },
    { q: "Noble gases are found in which group?", a: "Group 18", o: ["Group 18", "Group 1", "Group 17", "Group 16"] },
    { q: "Rust is chemically known as?", a: "Fe₂O₃·xH₂O", o: ["Fe₂O₃·xH₂O", "FeCl₃", "FeO", "Fe₃O₄"] },
    { q: "A catalyst changes the rate of reaction by?", a: "Lowering activation energy", o: ["Lowering activation energy", "Increasing temperature", "Adding more reactants", "Changing products"] },
  ],

  /* ══════════════════════════════════════════
     SET 4 — Biology
  ══════════════════════════════════════════ */
  set4: [
    { q: "The basic unit of life is?", a: "Cell", o: ["Cell", "Atom", "Organ", "Tissue"] },
    { q: "Which organelle contains the genetic material?", a: "Nucleus", o: ["Nucleus", "Mitochondria", "Ribosome", "Vacuole"] },
    { q: "What is the full form of DNA?", a: "Deoxyribonucleic Acid", o: ["Deoxyribonucleic Acid", "Diribonucleic Acid", "Deoxyribose Acid", "Dynamic Nuclear Acid"] },
    { q: "Photosynthesis occurs in?", a: "Chloroplasts", o: ["Chloroplasts", "Mitochondria", "Nucleus", "Cell Wall"] },
    { q: "How many chambers does the human heart have?", a: "4", o: ["4", "2", "3", "6"] },
    { q: "The largest organ in the human body?", a: "Skin", o: ["Skin", "Liver", "Brain", "Lungs"] },
    { q: "Which blood cells fight infections?", a: "White Blood Cells", o: ["White Blood Cells", "Red Blood Cells", "Platelets", "Plasma cells"] },
    { q: "Insulin is produced by?", a: "Pancreas", o: ["Pancreas", "Liver", "Kidney", "Thyroid"] },
    { q: "The process by which cells divide is called?", a: "Mitosis / Meiosis", o: ["Mitosis / Meiosis", "Osmosis", "Diffusion", "Transcription"] },
    { q: "Which vitamin helps in blood clotting?", a: "Vitamin K", o: ["Vitamin K", "Vitamin A", "Vitamin C", "Vitamin D"] },
    { q: "The study of heredity is called?", a: "Genetics", o: ["Genetics", "Ecology", "Physiology", "Taxonomy"] },
    { q: "Ribosomes are the site of?", a: "Protein synthesis", o: ["Protein synthesis", "Energy production", "DNA replication", "Fat synthesis"] },
    { q: "How many pairs of chromosomes in humans?", a: "23 pairs", o: ["23 pairs", "46 pairs", "22 pairs", "24 pairs"] },
    { q: "The longest cell in the human body?", a: "Neuron", o: ["Neuron", "Muscle cell", "Red Blood Cell", "Egg cell"] },
    { q: "Which organ filters blood in humans?", a: "Kidney", o: ["Kidney", "Liver", "Heart", "Spleen"] },
    { q: "What carries oxygen in blood?", a: "Hemoglobin", o: ["Hemoglobin", "Insulin", "Albumin", "Fibrinogen"] },
    { q: "The human brain is divided into how many main parts?", a: "3", o: ["3", "2", "4", "5"] },
    { q: "What is the process of gas exchange in lungs called?", a: "Respiration", o: ["Respiration", "Photosynthesis", "Digestion", "Absorption"] },
    { q: "Which part of the eye detects light?", a: "Retina", o: ["Retina", "Cornea", "Pupil", "Iris"] },
    { q: "The study of fungi is called?", a: "Mycology", o: ["Mycology", "Botany", "Zoology", "Virology"] },
    { q: "ATP stands for?", a: "Adenosine Triphosphate", o: ["Adenosine Triphosphate", "Adenine Triphosphate", "Amino Triphosphate", "Adenosine Trisphosphide"] },
    { q: "Mitochondria is known as?", a: "Powerhouse of the cell", o: ["Powerhouse of the cell", "Brain of the cell", "Skeleton of the cell", "Stomach of the cell"] },
    { q: "Which kingdom do bacteria belong to?", a: "Monera", o: ["Monera", "Protista", "Fungi", "Plantae"] },
    { q: "The movement of water across a semi-permeable membrane is?", a: "Osmosis", o: ["Osmosis", "Diffusion", "Active transport", "Facilitated diffusion"] },
    { q: "Bone is made mainly of?", a: "Calcium phosphate", o: ["Calcium phosphate", "Sodium chloride", "Magnesium sulphate", "Calcium carbonate"] },
    { q: "Which part of the neuron receives signals?", a: "Dendrite", o: ["Dendrite", "Axon", "Synapse", "Node of Ranvier"] },
    { q: "The human digestive system starts at?", a: "Mouth", o: ["Mouth", "Stomach", "Oesophagus", "Small intestine"] },
    { q: "Which gas is released during cellular respiration?", a: "CO₂", o: ["CO₂", "O₂", "N₂", "H₂"] },
    { q: "Enzymes are made of?", a: "Proteins", o: ["Proteins", "Lipids", "Carbohydrates", "Nucleic acids"] },
    { q: "The theory of evolution was proposed by?", a: "Charles Darwin", o: ["Charles Darwin", "Gregor Mendel", "Louis Pasteur", "Robert Hooke"] },
  ],

  /* ══════════════════════════════════════════
     SET 5 — General Knowledge
  ══════════════════════════════════════════ */
  set5: [
    { q: "How many continents are there on Earth?", a: "7", o: ["7", "5", "6", "8"] },
    { q: "Which is the largest ocean?", a: "Pacific Ocean", o: ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"] },
    { q: "The currency of Japan is?", a: "Yen", o: ["Yen", "Won", "Yuan", "Ringgit"] },
    { q: "The Great Wall is in which country?", a: "China", o: ["China", "Japan", "India", "Mongolia"] },
    { q: "Who wrote 'Romeo and Juliet'?", a: "William Shakespeare", o: ["William Shakespeare", "Charles Dickens", "Jane Austen", "Homer"] },
    { q: "What is the capital of France?", a: "Paris", o: ["Paris", "Lyon", "Nice", "Bordeaux"] },
    { q: "The Olympic Games are held every?", a: "4 years", o: ["4 years", "2 years", "3 years", "5 years"] },
    { q: "Which is the largest country by area?", a: "Russia", o: ["Russia", "Canada", "USA", "China"] },
    { q: "How many sides does a hexagon have?", a: "6", o: ["6", "5", "7", "8"] },
    { q: "Who painted the Mona Lisa?", a: "Leonardo da Vinci", o: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Van Gogh"] },
    { q: "The United Nations was founded in?", a: "1945", o: ["1945", "1939", "1950", "1919"] },
    { q: "What is the tallest mountain in the world?", a: "Mount Everest", o: ["Mount Everest", "K2", "Kangchenjunga", "Makalu"] },
    { q: "The speed of light is approximately?", a: "3 × 10⁸ m/s", o: ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "3 × 10¹⁰ m/s", "1.5 × 10⁸ m/s"] },
    { q: "Which planet is known as the Red Planet?", a: "Mars", o: ["Mars", "Jupiter", "Saturn", "Venus"] },
    { q: "How many letters are in the English alphabet?", a: "26", o: ["26", "24", "28", "25"] },
    { q: "The FIFA World Cup is held every?", a: "4 years", o: ["4 years", "2 years", "3 years", "5 years"] },
    { q: "Who invented the telephone?", a: "Alexander Graham Bell", o: ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"] },
    { q: "The smallest continent is?", a: "Australia", o: ["Australia", "Europe", "Antarctica", "South America"] },
    { q: "1 kilometre = ? metres", a: "1000", o: ["1000", "100", "10000", "500"] },
    { q: "What gas do we breathe in?", a: "Oxygen", o: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"] },
    { q: "Which country has the most population?", a: "India", o: ["India", "China", "USA", "Indonesia"] },
    { q: "The Eiffel Tower is in which city?", a: "Paris", o: ["Paris", "London", "Rome", "Berlin"] },
    { q: "What is 15% of 200?", a: "30", o: ["30", "25", "35", "20"] },
    { q: "Which is the longest river in the world?", a: "Nile", o: ["Nile", "Amazon", "Yangtze", "Mississippi"] },
    { q: "In which year did World War II end?", a: "1945", o: ["1945", "1939", "1918", "1950"] },
    { q: "What is the chemical symbol for water?", a: "H₂O", o: ["H₂O", "CO₂", "NaCl", "H₂O₂"] },
    { q: "How many planets are in our solar system?", a: "8", o: ["8", "9", "7", "10"] },
    { q: "Which is the hardest natural substance?", a: "Diamond", o: ["Diamond", "Gold", "Iron", "Granite"] },
    { q: "The primary colours of light are?", a: "Red, Green, Blue", o: ["Red, Green, Blue", "Red, Yellow, Blue", "Cyan, Magenta, Yellow", "Red, Orange, Violet"] },
    { q: "What is the square root of 144?", a: "12", o: ["12", "14", "11", "13"] },
  ],

};
